### ISSUE TITLE
Latest updates not showing

### ISSUE THREAD

**Issue by Hirojack** [DotBow/Blender-Version-Manager#11]
I just downloaded the Manager and it's suposed that the latest updates should be showing in the main window, but it shows nothing. I don't have any Blender build installed (the intention was to start using the manager to download Blender 2.8+) or network problems, and the log file shows an issue at "get_download_url".

[b3d_version_manager.log](https://github.com/DotBow/Blender-Version-Manager/files/3449409/b3d_version_manager.log)

**Comment by DotBow** [comment]
Hi!
Does this happen with latest 1.5.2 version?

**Comment by Hirojack** [comment]
This does happened in the 1.5.1 version. I cannot test if this is working properly in the latest 1.5.2 version because there is another issue (the program shows an "another instance is already running" prompt when opened).

**Comment by DotBow** [comment]
@Hirojack first you should quit BVM and delete previous version.

**Comment by DotBow** [comment]
Closing due to no owner response.
