### ISSUE TITLE
ValueError: time data does not match format on Linux

### ISSUE THREAD

**Issue by apoage** [DotBow/Blender-Version-Manager#13]
trying Linux version and it doesn't work like shows no version available  .. version 1.6.0

log below 

`ERROR:__main__:Uncaught exception
Traceback (most recent call last):
  File "check_for_updates.py", line 35, in run
  File "_strptime.py", line 571, in _strptime_time
  File "_strptime.py", line 359, in _strptime
ValueError: time data 'Wed, 25 Sep 2019 20:42:53 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
`

**Comment by DotBow** [comment]
Hi! Could you please provide information about Linux version. I suppose this is happening on Mint OS.

**Comment by apoage** [comment]
Ubuntu Studio 19.10 ... sorry i was out of reach

**Comment by DotBow** [comment]
Should be fixed in 1.61 Beta, commit 3de0b07.
