### ISSUE TITLE
Feature Request: Support additional branches

### ISSUE THREAD

**Issue by benthillerkus** [DotBow/Blender-Version-Manager#14]
Recently the Buildbot started to generate builds for branches that are planned for merging too:
[builder.blender.org/download/branches](https://builder.blender.org/download/branches/)

It would be nice to be able to download and manage these too

**Comment by DotBow** [comment]
Hi!
I'm aware of this feature, but doesn't have enough time right now to manage it.
Hope soon I will implement branching in BVM.
