### ISSUE TITLE
Feature Request: Support 2.81 Beta and 2.82 Alpha

### ISSUE THREAD

**Issue by benthillerkus** [DotBow/Blender-Version-Manager#15]
Check out [builder.blender.org](https://builder.blender.org/download/): They've added both branches because of their new release cycles scheme.
Does your current system theoretically support having multiple different versions to download? Writing the web scrapers is easy, but I don't want to setup the build environment with QT and stuff for myself.

**Comment by DotBow** [comment]
Hi!
Yep, scrapping itself is easy, but a proper UI and file management is bigger deal. I will look in to it as soon as I have free time. I'm interested in having access to all available builds too.
