### ISSUE TITLE
2.83 Alpha

### ISSUE THREAD

**Issue by Blenux** [DotBow/Blender-Version-Manager#17]
Just wondering if 2.83 Alpha will be added to the manager?

![Annotation 2020-01-13 134427](https://user-images.githubusercontent.com/25260650/72230624-daffee00-360a-11ea-9f3b-cc644c12f756.png)

Cheers.

**Comment by DotBow** [comment]
Hi!
Sorry, but not in BVM. Check this [post ](https://blenderartists.org/t/external-program-blender-version-manager-for-2-8/1128142/143?u=dotbow)for more information.
