### ISSUE TITLE
Bug: Version Manager stuck on "Finishing..." after download

### ISSUE THREAD

**Issue by theoldben** [DotBow/Blender-Version-Manager#19]
![image](https://user-images.githubusercontent.com/28691830/72665340-bd19fb00-3a07-11ea-9097-324094480358.png)
Upon downloading the latest version, BVM keeps getting stuck in the Finishing...-State.
The downloaded build is usable, but cannot be accessed from the panel. 
Trying to close BVM throws the "Update in progress!" error.
![image](https://user-images.githubusercontent.com/28691830/72665364-1b46de00-3a08-11ea-921e-72dbf21beb32.png)

**Comment by DotBow** [comment]
Hi!
Please, provide a log to make it easier to track a bug https://github.com/DotBow/Blender-Version-Manager/wiki/Blender-Version-Manager-Wiki#report-a-bug.
As for now you can kill BVM via task manager and try to download again.

**Comment by theoldben** [comment]
Thank you! That is my current workaround. 
This is the text of the latest logfile titled "BVM_Report_2020-01-24_22-38-41.log"

```
ERROR:__main__:Uncaught exception
Traceback (most recent call last):
  File "build_loader.py", line 129, in run
  File "pathlib.py", line 1319, in rename
PermissionError: [WinError 5] Access is denied: 'E:\\blender-2.82-18343c230d2c-windows64' -> 'E:\\Git-18343c230d2c-24-Jan-11-47'

```

**Comment by DotBow** [comment]
Hi!
It's been a while. Do you still have this issue?

**Comment by theoldben** [comment]
Yes. After every download. I usually just restart the manager then.

**Comment by DotBow** [comment]
The *PermissionError: [WinError 5] Access is denied:* can be caused by UAC. Check if you use system folder for storing builds or trying to execute BVM as admin. Also, try to move your builds to separate folder, not on root of E drive.

**Comment by DotBow** [comment]
Hi!
No new information provided, but new version at [Blender Launcher](https://github.com/DotBow/Blender-Launcher) repository should not have such issue.
