### ISSUE TITLE
Ошибка в дате после загрузки билда

### ISSUE THREAD

**Issue by koloved** [DotBow/Blender-Version-Manager#2]
Собственно вот скриншот, до загрузки дата нормальная, после она возращается на вчерашнюю
![Screenshot_58](https://user-images.githubusercontent.com/22406105/55479204-3e91cf80-5626-11e9-9da6-7251583df949.jpg)

**Comment by DotBow** [comment]
Привет!

Когда отображается новая версия для загрузки, дата совпадает с временем загрузки на сервер.
Для локальных версий он показывает дату коммита (такую же, как на заставке блендера), потому что время загрузки на сервер является случайным и не имеет особого смысла.
Дата коммита и дата загрузки на сервер разные.
