### ISSUE TITLE
Feature Request: Version Number

### ISSUE THREAD

**Issue by theoldben** [DotBow/Blender-Version-Manager#20]
The Commit Number is rather cryptic. Would it be hard to add the Build Number to the list? like 
**2.82.6**  Git-5472ae6fdfff6 | **17-Jan-18:59**

**Comment by DotBow** [comment]
Added here https://github.com/DotBow/Blender-Version-Manager/commit/fc6ab3b418c93f1e8e9314289edaa066787de906 :smirk:
