### ISSUE TITLE
Linux Version Issue

### ISSUE THREAD

**Issue by Blenux** [DotBow/Blender-Version-Manager#21]
Hi, I think there is a issue with the linux version of BVM, it only seems to detect the extracted folder and not the .tar.xz or .zip files , is this intentional or is it ment to detect them?, I've notice in Windows it would pick up the .zip.

Thanks.

![bvu](https://user-images.githubusercontent.com/25260650/74616914-95d95980-517e-11ea-8149-a62d288e951a.png)

**Comment by DotBow** [comment]
Hi!
This is an intended behavior: find new build on server -> download & extract -> use folders with blender.exe inside.
You'd better pick a separate folder for using only with BVM.
