### ISSUE TITLE
using colormanagement path as version name

### ISSUE THREAD

**Issue by dreisicht** [DotBow/Blender-Version-Manager#24]
I have created a ocio system path, and since then the version manager looks like this:

![image](https://user-images.githubusercontent.com/15658640/76678373-8ca1a800-65d7-11ea-9286-05a89afbdc10.png)

**Comment by DotBow** [comment]
Hi!
Sorry for late response. I'm not familiar with ocio system path. As far as I can see it changed the system path representation somehow. If you have more info on problem please let me know.

**Comment by dreisicht** [comment]
The ocio path, is a defined system path, where the colormanagement files of Blender lay.
Of course this has nothing to do with the folder, blender version manager is in, or puts the blender verions in, but somehow he takes that path from the system variables.

This is a screenshot how my ocio path is defined:
![image](https://user-images.githubusercontent.com/15658640/78540403-66e17a80-77f4-11ea-8639-61c31b39e97a.png)

**Comment by DotBow** [comment]
Hi!
You can check if new project solving an issue - [Blender Launcher](https://github.com/DotBow/Blender-Launcher)

**Comment by dreisicht** [comment]
Yes, it's solved!
