### ISSUE TITLE
MUP certificates (Serbia) lead to SSL error getting downloads from server

### ISSUE THREAD

**Issue by stotka1** [DotBow/Blender-Version-Manager#27]
Opened BVM 1.6.1 Beta doesnt show any release to download. Tried waiting a day (Maybe it needs a fresh blender version, although I know it doesnt usually work that way from what I remember). Still nothing. 
Any workaround? I really want the function of having Blender version instead of Git-

Edit: Tried previous version too. Doesnt work anymore. I have done a fresh win10 install recently. It must be a problem on my end. 

Thanks for the awesome product!

**Comment by DotBow** [comment]
Hi!
Do you have this issue for now?
Could you please send me log file as described here - [Report a Bug](https://github.com/DotBow/Blender-Version-Manager/wiki/Blender-Version-Manager-Wiki#report-a-bug) - so I can get more details about problem.

**Comment by stotka1** [comment]
[BVM_Report_2020-04-03_00-47-32.log](https://github.com/DotBow/Blender-Version-Manager/files/4424471/BVM_Report_2020-04-03_00-47-32.log)
Here you go. Its still not working.

**Comment by DotBow** [comment]
What region are you from and what OS using? It seem there is some weird SSL error happening...
Do you have access to [https://builder.blender.org/download/](https://builder.blender.org/download/) on you browser? If you are from Serbia try uninstall "Čitač elektronske lične karte" (found on forum, might be wrong)

**Comment by stotka1** [comment]
Damn, If that app is the culprite than thats insane! Its a smart card reader driver and I kind of need it. But now I remember I recently did a fresh win10 so it shouldnt be on my system. Im currenty in China and in general Im using a VPN. But I tried without the VPN but still no responese

**Comment by DotBow** [comment]
Yes, it's insane, but that's all that i can found about that issue since it is outside of BVM :confused:
"It seems that like everything in this country certificates issued by Ministry of Internal Affairs are messed up. Solution was to open  certmgr search for MUP and delete all their certificates."
Hope that can help.

**Comment by stotka1** [comment]
Thanks!

**Comment by DotBow** [comment]
So, closing issue, glad your problem fixed!
