### ISSUE TITLE
Issues installing in Ubuntu

### ISSUE THREAD

**Issue by Crikster** [DotBow/Blender-Version-Manager#29]
seems like the linux version is still the exe from windows perhaps? or maybe am doing something wrong? can you point out installation steps? thanks!!

**Comment by DotBow** [comment]
Hi!
Are you trying this one [Blender_Version_Manager_v1.6.1_Beta_Linux_x64.zip](https://github.com/DotBow/Blender-Version-Manager/releases/download/1.6.1beta/Blender_Version_Manager_v1.6.1_Beta_Linux_x64.zip)?
It is an executable for Unix systems. What exactly is going wrong?

**Comment by DotBow** [comment]
No further information posted, so closing the issue. 
You can visit [Blender Launcher](https://github.com/DotBow/Blender-Launcher) repository for new versions.
