### ISSUE TITLE
BVM Does not handle UAC

### ISSUE THREAD

**Issue by SilentPenguin** [DotBow/Blender-Version-Manager#3]
When downloading to a root folder protected by access control (such as C:/Program Files/Blender Foundation), BVM v1.4.1 will crash when attempting to start the download.

As a workaround, starting BVM with administrative privileges sidesteps this issue.

To address this issue, BVM should make a request to UAC to gain write privileges on the root folder when attempting to write to a folder protected with access control.

**Comment by DotBow** [comment]
It seems to be fixed using development version of PyInstaller:
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
I will roll out new version using it.

**Comment by DotBow** [comment]
So, I dug more into problem and my point is you never should use UAC protected folders for placing "Blender Version Manager.exe" or builds. There is no any good reason for these. Blender itself don't work well with administrative privileges since it blocks drag'n'drop functionality.
