### ISSUE TITLE
BVM constantly crashing when Root Folder is invalid

### ISSUE THREAD

**Issue by atgcab** [DotBow/Blender-Version-Manager#5]
Here is the log:

ERROR:__main__:Uncaught exception
Traceback (most recent call last):
  File "main.py", line 43, in <module>
  File "main.py", line 33, in main
  File "main_window.py", line 107, in __init__
  File "main_window.py", line 212, in collect_versions
  File "version_layout.py", line 124, in __init__
TypeError: 'NoneType' object is not subscriptable

**Comment by DotBow** [comment]
Hi!

Please, write where you placed your root folder.
Check that you not using UAC protected folders or admin mode.

**Comment by atgcab** [comment]
Hi,

I placed it on my second hard drive (D:), in a regular folder where I keep most of my programs. But I've tried other folders and the error persist.

Thanks.

**Comment by DotBow** [comment]
Do you have anything else in root folder?
It should be clean on first start.
Does this happening when opening program or after loading new build of Blender?

**Comment by DotBow** [comment]
Does this happening after loading new build  and/or after starting program?
I will do a deeper look at it as soon as I can (about 8 hours from now)
This bug seems to be related to Windows somehow.
Try to reboot OS if haven't done it for along time.

**Comment by atgcab** [comment]
This happens when I start the program. I have to say though that the first time I executed the program it worked but then I decided to move the executable from one folder where I downloaded it to the one where I have most of my programs (both folders are in D:). Then I restarted it from this new folder and the error appeared.

Yes, I have restarted Windows and still get the same error.

**Comment by DotBow** [comment]
Please, try to run this version: https://drive.google.com/open?id=1UfNC7c5zRNOjSlaTYoSh6LZY6MWcE6Xa
It should create AdditionalInfo.log to help me find out more about error.

**Comment by atgcab** [comment]
Here it is:

[AdditionalInfo.zip](https://github.com/DotBow/Blender-Version-Manager/files/3194116/AdditionalInfo.zip)

**Comment by DotBow** [comment]
It seems you are using "D:/Programas" folder which contains old "blender-2.49b-win64-python26" build.
Please, set as Root Folder new **empty** folder (like "D:/Programas/2.8 builds").

**Comment by atgcab** [comment]
I have done it but the error persists. I also have tried to put it in several other folders.

[AdditionalInfo.txt](https://github.com/DotBow/Blender-Version-Manager/files/3194420/AdditionalInfo.txt)

**Comment by DotBow** [comment]
Are you just moving around a "Blender Version Manager.exe" or use "Select new Root Folder Button" as shown on [Wiki](https://github.com/DotBow/Blender-Version-Manager/wiki/Blender-Version-Manager-Wiki#main-layout)?

AdditionalInfo.txt still shows this path "D:/Programas/blender-2.49b-win64-python26/blender.exe".

**Comment by atgcab** [comment]
I can't even press any button since the program doesn't open. I'm stuck in step "2. Execute "Blender Version Manager.exe" after I've done step "1. Place "Blender Version Manager.exe" somewhere on hard drive": I first tried placing it inside "D:/Programas", as I've said, then in "D:/Programas/2.8 builds", as you suggested.

**Comment by DotBow** [comment]
Such a bad situation...
Thats what happend:
1. You placed "Blender Version Manager.exe" in "D:/Programas" where you have a "blender-2.49b-win64-python26"
2. Program automatically setted Root folder as "D:/Programas" and now it constantly fails because of "blender-2.49b-win64-python26" (I am wondering if you have any other builds in there)

Now you need to reset a root path somehow.

Thats what I suggesting right now.

Simple one: 
Delete or move to other place "blender-2.49b-win64-python26" folder

Advanced one:
1. Press Win+R
2. Type "regedit"
3. Press OK
4. Go to menu Edit -> Find 
5. Type "root_folder"
6. Press Find Next
You should see this:
![изображение](https://user-images.githubusercontent.com/32243930/57974733-2e636300-79ce-11e9-8dbd-1b40cc1f7dfd.png)
7. Right click on "root_folder" folder row and select Edit
8. Then change root path to new one ("D:/Programas/2.8 builds" as example)

After that you can restart BVM.
Sorry for such trouble, very tricky bug. Need a good solution to fix it.

**Comment by atgcab** [comment]
Great, now it worked! 
Thank you very much!

**Comment by DotBow** [comment]
> 
> 
> Great, now it worked!
> Thank you very much!

Thank you for finding a bug!

**Comment by atgcab** [comment]
I forgot to answer your question. Yes, I have other builds, each one in a folder inside D:/Programas. 
There are "D:\Programas\Blender Foundation", with is the latest Blender 2.79 that I currently work with, "D:\Programas\blender-2.49b-win64-python26", "D:\Programas\blender-2.78-windows64" and "D:\Programas\blender-2.80.0-git.b46245470f79-windows64".

**Comment by DotBow** [comment]
Thank you for information! Now I need to find a user friendly way of handling such situations 😎

**Comment by DotBow** [comment]
New project [Blender Launcher](https://github.com/DotBow/Blender-Launcher) handles invalid builds, so an issue is kinda solved 😃
