### ISSUE TITLE
Double click the icon tray not working if new version available but not downloaded

### ISSUE THREAD

**Issue by Lauloque** [DotBow/Blender-Version-Manager#7]
As soon as there is a new version available but you have not downloaded it, you can not double click the BVM tray icon to start up Blender, it simply does not do anything.

I guess it tries to start the last version available instead of the last versions on disk?

**Comment by Joshua-Tsang** [comment]
Seems to work just fine for me. 
Git-cc600de6695a (29-May) is the latest build that BVM shows, and the latest build i have downloaded on my computer is Git-fee600f47980 (31-May).
Double clicking the tray icon does launch the latest build i have downloaded.

**Comment by Lauloque** [comment]
Well, it worked today too, with 31 May's downloaded and 1 Jun available.  
Yesterday I had 30 May installed and 31 May available, no idea why it didn't work yesterday.

I guess this isn't an issue if it doesn't happen anymore. x)

**Comment by DotBow** [comment]
Closing due to no further bug appearance.
