### ISSUE TITLE
Can I run BVM as admin but not Blender?

### ISSUE THREAD

**Issue by lucianomunoz** [DotBow/Blender-Version-Manager#9]
Im having issues with my pentablet when i run blender with admin privileges, 
but i need to run Blender Version Manager with Admin privileges because otherwise it cant write the folder where the blender versions are stored (program files/blender/)
Is there a way to run BVM with admin privileges but when i hit a blender from there it not be open with the same privileges? maybe a tick box in the settings could be great.
thanks!

**Comment by DotBow** [comment]
Hi!
There is a note in the Wiki page: **don't use UAC protected folders like "C:\Program Files" for placing "Blender Version Manager.exe" or Root Folder. You can still use user folders like "Documents"**.
First, it is recommended to run Blender without admin rights. Second, it is better to hold root folder on non system drive. Running Blender from BVM is tight together on process level. There is no any good way on Windows to solve such complicated problem like UAC and still have all functionality working as intended.
